export * from './createI18n'
export * from './provider/I18nProvider'
export * from './store/I18nStore'
export { hookTranslatable as useTranslatable } from './translatable/hookTranslatable'
export { hocTranslatable as withTranslatable } from './translatable/hocTranslatable'
export { decoratorTranslatable as translatable } from './translatable/decoratorTranslatable'
export * from './observer'
export type { InjectedTransProps } from './translatable/hocTranslatable'